// PluginEditor.cpp
#include "PluginEditor.h"
#include "PluginProcessor.h"

//==============================================================================
AudioPluginAudioProcessorEditor::AudioPluginAudioProcessorEditor(
    AudioPluginAudioProcessor &p)
    : AudioProcessorEditor(&p), processorRef(p) {

  // 1. Initialize the component FIRST
  webView = std::make_unique<WebViewBridge>();

  // 2. Set up its properties
  addAndMakeVisible(webView.get());

  webView->setParameterCallback(
      [this](const juce::String &paramName, float value) {
        onParameterChangedFromJS(paramName, value);
      });

  // 3. ONLY THEN call setSize (which triggers resized())
  setSize(750, 500);

  // 4. Load your HTML/initial values after the UI is ready
  // Robust method: Extract BinaryData to a temp folder to avoid bundle path
  // issues

  auto tempDir =
      juce::File::getSpecialLocation(juce::File::tempDirectory)
          .getChildFile("AudioPlugin03_Resources_" +
                        juce::String(juce::Time::currentTimeMillis()));

  tempDir.createDirectory();

  // Helper to write binary data to file - explicitly using 'BinaryData::'
  // namespace
  auto unpackFile = [&](const char *data, int size,
                        const juce::String &filename) {
    auto file = tempDir.getChildFile(filename);
    file.replaceWithData(data, size);
    return file;
  };

  // Use the exact names generated by JUCE from filenames (dots replaced by
  // underscores usually, but simple names like these are often just name_ext)
  // Checking typical JUCE BinaryData naming conversion:
  // Resources/index.html -> index_html
  // Resources/script.js -> script_js
  // Resources/style.css -> style_css

  auto htmlFile = unpackFile(BinaryData::index_html, BinaryData::index_htmlSize,
                             "index.html");

  webView->goToURL("file://" + htmlFile.getFullPathName());

  // Clean up on destruction? The temp dir will remain, but OS cleans vars.
  // For a production plugin, you might check if they exist or use a fixed cache
  // dir.

  startTimerHz(60);
  sendGainToJS(processorRef.apvts.getRawParameterValue("gain")->load());
}

AudioPluginAudioProcessorEditor::~AudioPluginAudioProcessorEditor() {
  stopTimer();
}

//==============================================================================
void AudioPluginAudioProcessorEditor::paint(juce::Graphics &g) {
  // WebView will handle all rendering
  g.fillAll(juce::Colour(0xff1e1e1e));
}

//==============================================================================
void AudioPluginAudioProcessorEditor::resized() {
  // Only set bounds if the pointer actually exists!
  if (webView != nullptr) {
    webView->setBounds(getLocalBounds());
  }
}
//==============================================================================
void AudioPluginAudioProcessorEditor::timerCallback() {
  // Poll for parameter changes and send to JavaScript
  float currentGain = processorRef.apvts.getRawParameterValue("gain")->load();

  if (std::abs(currentGain - lastGainValue) > 0.01f) {
    lastGainValue = currentGain;
    sendGainToJS(currentGain);
  }
}

//==============================================================================
void AudioPluginAudioProcessorEditor::onParameterChangedFromJS(
    const juce::String &paramName, float value) {
  // Update the parameter in the processor
  if (paramName == "gain") {
    auto *param = processorRef.apvts.getParameter("gain");
    if (param != nullptr) {
      // Normalize the value to 0-1 range for JUCE parameter
      float normalizedValue = juce::jmap(value, -60.0f, 0.0f, 0.0f, 1.0f);
      param->setValueNotifyingHost(normalizedValue);
      lastGainValue = value; // Update cached value to prevent feedback loop
    }
  }
}

//==============================================================================
void AudioPluginAudioProcessorEditor::sendGainToJS(float gainDb) {
  // Convert gain from dB (-60 to 0) to percentage (0 to 100)
  float percentage = juce::jmap(gainDb, -60.0f, 0.0f, 0.0f, 100.0f);

  // Functions that comes from the bridge.ts file
  juce::String jsCode = "if (window.gainKnob) { window.gainKnob.setValue(" +
                        juce::String(percentage) + "); }";

  webView->evaluateJavascript(jsCode);
}
